# Generated by Django 3.1 on 2020-08-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reccomendationengine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationdatabase',
            name='image',
            field=models.ImageField(default=1, upload_to='animetitles'),
            preserve_default=False,
        ),
    ]
