# Generated by Django 3.1 on 2020-09-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reccomendationengine', '0003_auto_20200819_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationdatabase',
            name='imdb',
            field=models.FloatField(default=0),
        ),
    ]
