# Generated by Django 3.1 on 2020-08-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200815_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='anime_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='votes',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
