# Generated by Django 3.1 on 2020-08-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_list2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='List2020',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('anime_id', models.IntegerField(default=10)),
                ('summary', models.TextField(default='I am summary')),
                ('no_of_episodes', models.IntegerField(default=100)),
                ('dubbing', models.BooleanField(default=False)),
                ('images', models.ImageField(upload_to='animetitles')),
                ('rating', models.IntegerField(default=10)),
                ('link_crunchyroll', models.URLField()),
                ('link_imdb', models.URLField()),
                ('link_shop', models.URLField()),
                ('season', models.TextField(max_length=10)),
                ('up_votes', models.IntegerField(default=10)),
                ('down_votes', models.IntegerField(default=10)),
            ],
        ),
    ]
