# Generated by Django 3.1 on 2020-08-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_list2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list2020',
            name='season',
            field=models.CharField(max_length=10),
        ),
    ]
