# Generated by Django 3.1 on 2020-09-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200819_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='user_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
