# Generated by Django 3.1 on 2020-08-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List2018',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('summary', models.TextField(default='I am summary')),
                ('no_of_episodes', models.IntegerField(default=100)),
                ('dubbing', models.BooleanField(default=False)),
                ('images', models.ImageField(upload_to='')),
                ('rating', models.IntegerField(default=10)),
                ('link_crunchyroll', models.URLField()),
                ('link_imdb', models.URLField()),
                ('link_shop', models.URLField()),
            ],
        ),
    ]
