# Generated by Django 3.1 on 2020-08-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200816_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list2018',
            name='rating',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='list2019',
            name='rating',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='list2020',
            name='rating',
            field=models.FloatField(default=10),
        ),
    ]
