# Generated by Django 3.1 on 2020-08-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imdb', models.IntegerField(default=0)),
                ('summary', models.TextField()),
                ('Year2010', models.BooleanField(default=False)),
                ('genre', models.CharField(max_length=15)),
                ('sub_genre', models.CharField(max_length=15)),
            ],
        ),
    ]
