# Generated by Django 3.1 on 2020-08-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reccomendationengine', '0002_recommendationdatabase_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationdatabase',
            name='crunchyroll',
            field=models.URLField(default='www.theanimeradio.com'),
        ),
        migrations.AddField(
            model_name='recommendationdatabase',
            name='info',
            field=models.URLField(default='www.theanimeradio.com'),
        ),
    ]
