# Generated by Django 3.1.1 on 2020-09-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='choice',
            new_name='choice1',
        ),
        migrations.AddField(
            model_name='choices',
            name='choice2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choices',
            name='choice3',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choices',
            name='choice4',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choices',
            name='image1',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choices',
            name='image2',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choices',
            name='image3',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choices',
            name='image4',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choices',
            name='votes1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choices',
            name='votes2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choices',
            name='votes3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choices',
            name='votes4',
            field=models.IntegerField(default=0),
        ),
    ]
