# Generated by Django 3.1.1 on 2020-09-09 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0002_auto_20200909_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='choice1',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='choices',
            old_name='image1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='choices',
            old_name='votes1',
            new_name='votes',
        ),
        migrations.RemoveField(
            model_name='choices',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='choices',
            name='choice3',
        ),
        migrations.RemoveField(
            model_name='choices',
            name='choice4',
        ),
        migrations.RemoveField(
            model_name='choices',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='choices',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='choices',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='choices',
            name='votes2',
        ),
        migrations.RemoveField(
            model_name='choices',
            name='votes3',
        ),
        migrations.RemoveField(
            model_name='choices',
            name='votes4',
        ),
    ]
