# Generated by Django 3.1.1 on 2020-09-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0003_auto_20200909_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='poll_des',
            field=models.TextField(default=12312),
            preserve_default=False,
        ),
    ]
