# Generated by Django 3.1.1 on 2020-09-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0005_auto_20200909_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='choicedetail',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
